In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
df = pd.read_csv(r"C:\Users\famir\Desktop\Pokemon.csv")
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [3]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [4]:
df[['Name','Attack','Type 1']]

                      Name  Attack   Type 1
0                Bulbasaur      49    Grass
1                  Ivysaur      62    Grass
2                 Venusaur      82    Grass
3    VenusaurMega Venusaur     100    Grass
4               Charmander      52     Fire
..                     ...     ...      ...
795                Diancie     100     Rock
796    DiancieMega Diancie     160     Rock
797    HoopaHoopa Confined     110  Psychic
798     HoopaHoopa Unbound     160  Psychic
799              Volcanion     110     Fire

[800 rows x 3 columns]

In [5]:
df.iloc[1]['Name']

'Ivysaur'

In [6]:
df.head(12)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False

In [7]:
df.index[745:750]

RangeIndex(start=745, stop=750, step=1)

In [8]:
df.loc[((df['HP']>80) & (df['Type 1'] == 'Fire'))]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False

In [9]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [10]:
df_s1 = df.sort_values(['Generation', 'Attack'] , ascending = [1,0])
df_s1[0:10]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
161,149,Dragonite,Dragon,Flying,600,91,134,95,100,100,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
74,68,Machamp,Fighting,NaN,505,90,130,80,65,85,55,1,False
107,99,Kingler,Water,NaN,475,55,130,115,50,50,75,1,False

In [11]:
df['Total Power'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] +df['Sp. Def'] + df['Speed']

In [12]:
df.sort_values(['Generation' , 'Total Power'], ascending = [1,0])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total Power
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True,780
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True,780
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True,680
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False,640
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,661,Fletchling,Normal,Flying,278,45,50,43,40,38,62,6,False,278
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False,245
727,659,Bunnelby,Normal,NaN,237,38,36,38,32,36,57,6,False,237
733,665,Spewpa,Bug,NaN,213,45,22,60,27,30,29,6,False,213
732,664,Scatterbug,Bug,NaN,200,38,35,40,27,25,35,6,False,200

In [13]:
df.loc[((df['Type 1'] == 'Fire') & (df['Total Power']>500))].sort_values('Total Power',ascending =False )

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total Power
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True,680
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,634
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,634
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False,630
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,600
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True,600
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True,580
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True,580
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False,560
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False,555
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False,540
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False,540
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False,534
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,534
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False,534
171,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False,534
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False,530
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False,528
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False,525
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False,507
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False,505

In [14]:
df = df.drop(columns='Total')

In [15]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total Power
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [16]:
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]] + cols[4:-1]]
df

,#,Name,Type 1,Type 2,Total Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [17]:
df.to_csv(r"C:\Users\famir\Desktop\Pokemon_m1.csv" , index=False)

In [18]:
TP = df['Total Power']

In [19]:
type(TP)

pandas.core.series.Series

In [20]:
df_f1 = df.loc[(df['Type 1']=='Fire') | (df['Total Power']>700)]

In [21]:
df_f1.reset_index(drop=True,inplace=True)

In [22]:
df_f1

,#,Name,Type 1,Type 2,Total Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
1,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
2,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
3,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
4,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
5,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
6,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
7,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
8,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
9,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
10,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
11,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
12,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
13,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
14,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
15,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
16,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
17,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
18,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False
19,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
20,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
21,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
22,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
23,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
24,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
25,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
26,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
27,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
28,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
29,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
30,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
31,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
32,382,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True
33,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
34,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
35,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False
36,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
37,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
38,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
39,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
40,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
41,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
42,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
43,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
44,513,Pansear,Fire,NaN,316,50,53,48,53,48,64,5,False
45,514,Simisear,Fire,NaN,498,75,98,63,98,63,101,5,False
46,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
47,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
48,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
49,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
50,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
51,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
52,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
53,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
54,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
55,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
56,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
57,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [23]:
df.loc[df['Type 1']=='Green' , 'Type 2']='Green_2'

In [24]:
df

,#,Name,Type 1,Type 2,Total Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [25]:
df.head(20)

,#,Name,Type 1,Type 2,Total Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False

In [26]:
#df.loc[df['Name'].str.contains('(wee).*' ,flags= re.I ,regex=True)]

In [27]:
df['Name'].replace(to_replace=r'[wee Wee](.*)', value='FAR\g<1>', regex=True, inplace=True)

In [28]:
df.head(20)

,#,Name,Type 1,Type 2,Total Power,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,VFARnusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VFARnusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,CharmandFARr,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,CharmFARleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMFARga Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMFARga Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,SquirtlFAR,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,FARartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,BlastoisFAR,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoisFARMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,CatFARrpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,MFARtapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,ButtFARrfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,FAReedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
18,15,BFARedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BFARedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False

In [ ]:
new_df = pd.read_csv(r"C:\Users\famir\Desktop\Pokemon.csv", chunksize=5)
main_df = pd.DataFrame(columns=new_df.columns)

In [32]:
df_chunked